### PR TITLE
Automation Script for Running the Scraper

### PR DESCRIPTION
**Pull request by Mohamed-SayedAlAhl**
## Description:

I have implemented a script, exe_script.py, to enhance the functionality of the Educative.io Scraper project. This script serves to automate the execution of the Python scraper file through the utilization of the standard Python module, "subprocess."

## Key Features:

The script streamlines the process of running the Python scraper (EducativeScraper.py) by automating the necessary steps.

## Usage Instructions:

After configuring the paths within the script, users can employ it in conjunction with an icon of their choice. They can then execute the following pyinstaller command to create an executable file that opens the Scraper GUI:

pyinstaller --noconfirm --onefile --console --icon "icon.ico"  "exe_script.py"

This enhancement aims to simplify the execution of the scraper, making it more accessible and user-friendly.

### CODE REVIEW

**Comment by anilabhadatta** [comment]
@Mohamed-SayedAlAhl clone latest repo, made multiple changes

**Comment by Mohamed-SayedAlAhl** [comment]
@anilabhadatta 

Done merged the changes

**Comment by anilabhadatta** [comment]
@Mohamed-SayedAlAhl may i know why this script is required?
activating the venv is only required once you open a terminal, rest of time you can just type the python EducativeScraper.py to start the app.
I will look into the pyinstaller one that you have mentioned.
Currently there is a bug that i am now looking at this moment.

**Comment by Mohamed-SayedAlAhl** [comment]
@anilabhadatta 
I made it for my self so I don't have to get into the folder and run "python EducativeScraper.py " every time
by using exe that refers to the folder and run the scraper for me I can run it from any where in my pc by simply opening the exe and it will do all of it for me.

I don't know what you mean by activating the env once, for me I am using conda env and I have to activate it every time I run the python file and in addition I have to open the folde or go to the path from cmd which taking time.

I think by using this will make it more quick to open the GUI without having to go to the path or running cmd or using any code editors.

**Comment by Mohamed-SayedAlAhl** [comment]
@anilabhadatta 
After changing the required paths inside the script to match your paths and then turning the script into exe, Running the GUI will be easy and quick like this:

https://app.screencast.com/S6e8nPfC8ZmOK

**Comment by anilabhadatta** [comment]
> @anilabhadatta After changing the required paths inside the script to match your paths and then turning the script into exe, Running the GUI will be easy and quick like this:
> 
> https://app.screencast.com/S6e8nPfC8ZmOK

looks good but there needs some improvements like clicking on cross button will clear the temp directory or not,
there could be a setup.py which will create a virtual env and install the requirements and then create the app using pyinstaller.
now using the exe it will load the venv and then run the script
I actually want a solution where you can just update the path and the exe will work at any given path, maybe you will need to add the path to the OS Path while using setup.py

Idea:
<setup.py install> in default will install it inside the default python site-packages folder, but it should also contain an uninstall method to remove everything from that folder. There could be a argument like customPath where you can install the packages.
The currentPath where it is installed should be updated in OS environment Path so that while creating a exe with pyinstaller will run the EducativeScraper.py from that currentPath.
So your exe is path independent and the setup.py install will handle everything like installing venv, requirements.txt etc.
Or much better, create an executable like setup.py using tkinter, which can install everything.

**Comment by Mohamed-SayedAlAhl** [comment]
@anilabhadatta 

" clicking on cross button will clear the temp directory"
where is this temp directory?
do u mean "C:\Users\user name\AppData\Local\Temp"?

"update the path and the exe will work at any given path, maybe you will need to add the path to the OS Path while using setup.py"
I didn't understand what you mean, It is already doing that u will specify the path of the python file and then when running it from anywhere it will work. It is independent of its current path of the exe!

You want it to do all installation! oh that is big. I am currently trying to make it create the env on its own but still not working properly

**Comment by anilabhadatta** [comment]
@Mohamed-SayedAlAhl i have implemented a solution, lets see if it works

**Pull request closed without merging**
