### PR TITLE
Refactor and scrape all urls

### PR DESCRIPTION
**Pull request by abhinavm24**
@anilabhadatta I had started putting together the method to scrape all url - src/Utility/CourseUtil.py
Rest are minor changes that you can ignore or keep if you want

### CODE REVIEW

**Comment by anilabhadatta** [comment]
@abhinavm24 may i know why are you taking start index?
Also a lot of data were hard-coded and it is not allowed.
Adding comments is allowed.
Changing architecture is not allowed.
May i know which features are you trying to implement?

**Comment by abhinavm24** [comment]
I know, I've not fixed all the problems, just got the scrape all urls
it's under src/Utility/CourseUtil.py

**Comment by anilabhadatta** [comment]
@abhinavm24 scrape first topic url of every course?

**Comment by anilabhadatta** [comment]
@abhinavm24 I have more or less understood your PR,
You have implemented the get api url and then scraped the data from it.
I think this is not needed because a lot of data is like slides, hints etc are difficult to obtain so it is better to scrape the html page and only collect necessary info like title, codes, quiz etc from api.
these are already implemented so i dont find it to implement it again using bs4.

secondly scrapealltopicurls is actually getting the first topic link of each course from educative.io
suppose a text file will be created and it will contain all the first topic links of each and every course available in educative.
I have thought about a workaround using api but difficult to implement.
and i saw that main function was written on start method, it is not alloewed since start function is called from a different module.

I liked your comments though so i may merge the comments after a discussion,
since you have contacted me on tg, do text me there, i will explain a bit more and maybe we can upgrade this.
i need to get your thoughts about a better efficient method.

**Comment by anilabhadatta** [comment]
@abhinavm24 pushed new commit, bug fixes mostly
also i will recommend you to redownload chrome binary and driver and delete the userdatadirectory
i saw that newer chrome causes cloudflare to start giving unlimited captchas, so i disabled the update chrome urls functionality and hardcoded version 116 which may fix the cloudflare issue.
although testing is required and cloudflare may pop up after multiple requests from same IP.

**Comment by abhinavm24** [comment]
Yes, I've not followed all your patterns. Feel free to pick the pieces that you want.

The url list created is exhaustive and can be used to get to the next page quickly and avoid the script execution to get the next link(this is slow in test browser instance), the rest of the API data can be used in your viewer project

**Comment by anilabhadatta** [comment]
@abhinavm24 I have pushed some fixes.
I have contacted you on telegram, please check.
For the time being can you reclone the current repo to a different location and only add the comments and create a new PR for it.

**Comment by anilabhadatta** [comment]
@abhinavm24 what is the purpose of the latest commit? I couldn't understand the use of vault.

**Comment by abhinavm24** [comment]
@anilabhadatta I had started working on something entirely different and updated the branch, forgot that it is referenced in your repo's PR

**Comment by anilabhadatta** [comment]
@abhinavm24 no issues. feel free to commit if you have any better ideas.
I have almost completed it except one feature implementation. Not planned as of now.
Will redesign the leetcode-scraper in a few days time.

**Pull request closed without merging**
