### PR TITLE
Full Automation Setup

### PR DESCRIPTION
**Pull request by Mohamed-SayedAlAhl**
The setup.py must be runned first and It will do the following:

- ask the user for the folder containing EducativeScraper.py to know where all files will be
- create virtual env
-  install all dependencies from requirements.txt in addition to pyinstaller  that will be used later for creating exe
- create  temp folder called "executable" and make python script that has path independency and copy the icon inside it to cover the exe later.
- generate the exe using the script and make the icon.ico as its icon.
- show the user that the exe is in dist folder and delete the folder that contained the script as it is no longer needed.
-  use the exe in any folder or partition and it will run smoothly not depending in the path it is in.

### CODE REVIEW

**Comment by Mohamed-SayedAlAhl** [comment]
@anilabhadatta 

Take a look at this one, I have used tkinter for the implementation here.
I tested it and it works.

**Comment by anilabhadatta** [comment]
@Mohamed-SayedAlAhl  looking into it

**Comment by anilabhadatta** [comment]
@Mohamed-SayedAlAhl I understood what you did but it is only windows only system.
Check my setup.py
maybe you can implement the pyinstaller process there.

**Comment by anilabhadatta** [comment]
I think tkinter is not needed since it is known that script.py will be inside project dir.

**Comment by Mohamed-SayedAlAhl** [comment]
@anilabhadatta 
will upload it now will close this and open new one and also to pull your updates too

**Comment by anilabhadatta** [comment]
@Mohamed-SayedAlAhl No need to do it, I have implemented the solution, took some help from your code. Thank you..

**Comment by anilabhadatta** [comment]
will push in few minutes

**Pull request closed without merging**
